"""Kinds bus Memory V2 — enregistrement dans bus.DEFAULT_POLICIES."""

MEMORY_STORED = "MEMORY_STORED"
MEMORY_RECALLED = "MEMORY_RECALLED"
MEMORY_FORGOTTEN = "MEMORY_FORGOTTEN"
MEMORY_REJECTED = "MEMORY_REJECTED"
MEMORY_STORE_REJECTED = "MEMORY_STORE_REJECTED"

MEMORY_KINDS: tuple[str, ...] = (
    MEMORY_STORED,
    MEMORY_RECALLED,
    MEMORY_FORGOTTEN,
    MEMORY_REJECTED,
    MEMORY_STORE_REJECTED,
)
